🍰 Create Smartphone Parser
memhard/smartsite pull request #2
Opened 2024-03-04 22:13 UTC by Olderestin

## What changed?     
- Create smarphone parser using requests and bs4

## Checklist before requesting a review     
- [x] I have performed a self-review of my code
- [x] Code is functional on my machine(Windows 10/Debian GNU/Linux 11 (bullseye))

2024-04-02 19:03 UTC, DmitroPodolsky requested changes
Need changes!

2024-04-02 19:03 UTC, memhard commented on src/phone/parser/models.py
> +from mixins import DownloadCharacteristicsMixin
why don't use * if you use all classes there

2024-04-02 19:03 UTC, DmitroPodolsky commented on src/phone/parser/mixins.py
> +    # Штучний інтелект
why comments on uk?

2024-04-02 19:03 UTC, DmitroPodolsky commented on src/phone/parser/utils.py
> +    smartphone_characteristics_dict  = {}
bad naming

2024-04-02 19:03 UTC, DmitroPodolsky commented on src/phone/parser/utils.py
> +        print("ValidationError: ", e)
use loguru for logs

2024-04-06 15:12 UTC, Olderestin reviewed
Changes done.

2024-04-06 15:37 UTC, DmitroPodolsky requested changes
need changes in docs!

2024-04-06 15:37 UTC, DmitroPodolsky commented on src/phone/parser/utils.py
> +        list[str]: List of photo URLs.
we doesn't need to write what type of data we're returning in docstring

2024-04-06 15:37 UTC, DmitroPodolsky commented on src/phone/parser/mixins.py
> +    # Основна камера
in class

``` python
class WirelessTechnologyCharacteristicsMixin(BaseModel):
    """
    Mixin class for representing wireless technology characteristics of a smartphone.
    
    Original name of the characteristic on the website: Бездротові технології
    """
    wi_fi: str | None = Field(alias="Wi-Fi", default=None)
    satellite_system: str | None = Field(alias="Супутникова система", default=None)
    bluetooth: str | None = Field(alias="Bluetooth", default=None)
    nfc: str | None = Field(alias="NFC", default=None)
    infrared_port: str | None = Field(alias="Інфрачервоний порт", default=None)
```
there another logic of docstring, why?

2024-04-07 10:33 UTC, DmitroPodolsky approved these changes
LGTM 👍  but need fix docstrings in Returns

2024-04-07 10:33 UTC, merged