🍰 Feature/auth
memhard/smartsite pull request #4
Opened 2024-03-31 11:25 UTC by DmitroPodolsky

## What changed?
add jwt autharization, change models, add user registration and etc changes...     

## Issue ticket(s) number and link     
- Resolves No link 
     
## Checklist before requesting a review     
- [ ] I have performed a self-review of my code           
- [ ] Code is functional on my machine(Windows 11/Ubuntu22.04 LTS)

2024-04-03 18:28 UTC, Olderestin reviewed
Make changes and can aprove 👍

2024-04-03 18:28 UTC, Olderestin commented on src/auth/manager.py
> +async def verified_user(token: str = Depends(oauth_scheme), session: AsyncSession = Depends(get_async_session)) -> User:
Change func name

2024-04-03 18:28 UTC, Olderestin commented on .env.example
> +
```suggestion
PGADMIN_DEFAULT_EMAIL = 'postgres@postgres.com'
PGADMIN_DEFAULT_PASSWORD = 'postgres'
```
Add pgadmin settings

2024-04-08 19:37 UTC, Olderestin requested changes
Need changes.

2024-04-08 19:37 UTC, Olderestin commented on src/auth/routers.py
> +async def logout(data: str = Depends(get_token_data), session: AsyncSession = Depends(get_async_session)):
I think we can use current_user Depends already

2024-04-08 19:37 UTC, Olderestin commented on requirements.txt
> -requests
Why do you change requirements?

2024-04-08 19:37 UTC, Olderestin commented on src/auth/manager.py
> +                detail='not a refresh token'
```suggestion
                detail='Not a refresh token'
```
Does it metter for front if they will wait for messages starting with capital letter?

2024-04-08 19:37 UTC, Olderestin commented on src/auth/manager.py
> +                detail='not an access token'
Same

2024-04-08 19:37 UTC, Olderestin commented on src/auth/manager.py
> +                detail='invalid authorization credentials'
Same

2024-04-08 19:37 UTC, Olderestin commented on src/auth/manager.py
> +                detail='token has been revoked'
Maybe we don't need to send details about it, just <<invalid credentials>>?

2024-04-08 19:48 UTC, DmitroPodolsky commented on src/auth/routers.py
> +async def logout(data: str = Depends(get_token_data), session: AsyncSession = Depends(get_async_session)):
fixed

2024-04-08 19:51 UTC, DmitroPodolsky reviewed
tasks done

2024-04-08 19:53 UTC, merged